In [7]:
import numpy as np


In [9]:
a = np.arange(15).reshape(3,5)


In [10]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
a.shape


(3, 5)

a.ndim


In [20]:

a.ndim

2

In [21]:
a.dtype.name

'int64'

In [22]:
a.size

15

In [23]:
type(a)

numpy.ndarray

In [24]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [25]:
type(b)

numpy.ndarray

In [27]:
a = np.array([1.2, 3.5, 5.1])
a

array([1.2, 3.5, 5.1])

In [28]:
a.dtype


dtype('float64')

In [29]:
print("Hello World")

Hello World


In [30]:
import math
print(math.sqrt(25))

5.0


In [31]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a.ndim)
print(a.size)

(3, 3)
2
9


In [33]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [35]:
np.random.rand(3,3)

array([[0.20559536, 0.34747407, 0.65569028],
       [0.12579583, 0.60479467, 0.07415204],
       [0.00731966, 0.30072582, 0.4973903 ]])

In [37]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a = np.arange(12)
b = a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)

[5 7 9]


In [44]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a @ b)

[[19 22]
 [43 50]]


In [46]:
a = np.array([10,20,30])
print(a[0])

10


In [47]:
a = np.array([1,2,3,4,5])
print(a[1:4])

[2 3 4]


In [49]:
a = np.array([[1,2,3],[4,5,6]])
print(a[1,2])

6


In [54]:
b = np.array([1,2,3,4,5,6])
print(b + 5)

[ 6  7  8  9 10 11]


In [56]:
a = np.array([1,2,3])

print(a*10)

[10 20 30]


In [62]:
a= np.array([0, 1, 4, 90])
print(a < 35)


[ True  True  True False]


In [64]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [70]:
a = np.ones((2,3,4))
a


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [72]:
a = np.arange(10, 30, 5)
a


array([10, 15, 20, 25])

In [74]:
a = np.linspace(0,2,9)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [76]:
A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])
A * B

array([[2, 0],
       [0, 4]])

In [77]:
A @ B

array([[5, 4],
       [3, 4]])

In [78]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [104]:
def function(x,y):
    return 10 * x + y
b = np.fromfunction(function, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [102]:
b[2, 1]

np.int64(11)

In [105]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [106]:
    b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [108]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [110]:
b = np.array([[0,1,2,3], [10,11,12,13]])
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13


In [111]:
b.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13])

In [112]:
b.T

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [114]:
a = np.array([1,2])
b = np.array([3,4])
np.vstack((a,b))


array([[1, 2],
       [3, 4]])

In [1]:
a = np.array([1,2])
b = np.array([3,4])
np.hstack((a,b))

NameError: name 'np' is not defined